CMakeLists.txt, test/schnorr-tests.c
This fixes the immediate issue. However, this is a good indication of how badly we need to update our tests.
=> Fix build issuer schnorr failing

src/amcl-extensions/pairing_BN254.c, src/credential_BN254.c, src/internal/schnorr.c, src/signature_BN254.c
Only convert points to affine form when necessary (after calls to `_add` or `_sub`), and not every time a pairing is computed.
resolves #8
=> Clarify when affine needs to be called.

include/ecdaa/issuer_keypair_BN254.h, include/ecdaa/member_keypair_BN254.h, include/ecdaa/signature_BN254.h, src/amcl-extensions/ecp2_BN254.c, src/amcl-extensions/ecp2_BN254.h, src/amcl-extensions/ecp_BN254.c, src/amcl-extensions/ecp_BN254.h, src/credential_BN254.c, src/issuer_keypair_BN254.c, src/member_keypair_BN254.c, src/signature_BN254.c
This is pedantic, but function declarations for functions that take no parameters should be `(void)`, not just `()` (as in C++).
=> Update all "length" functions to use void parameters.

test/member_keypair-tests.c
A couple of instances of calls to `ecdaa_prng_init` in our tests aren't getting their return values checked, which is being picked up by Coverity.
=> Check return values from _all_ ecdaa_prng_init's in tests.

include/ecdaa/credential_BN254.h, include/ecdaa/member_keypair_BN254.h, src/credential_BN254.c, src/member_keypair_BN254.c
- Fix credential deserialization.
- Allow two buffers (one for the credential, one for the credential_signature) for the`ecdaa_credential_BN254_deserialize_with_signature` function.
- Allow non-checking deserializer for member public key (so member itself can deserialize)
=> Improve serialization for member public key and credential

src/amcl-extensions/ecp2_BN254.c, src/amcl-extensions/ecp2_BN254.h, src/amcl-extensions/ecp_BN254.c, src/amcl-extensions/ecp_BN254.h, src/credential_BN254.c, src/group_public_key_BN254.c, src/internal/schnorr.c, src/signature_BN254.c, test/member_keypair-tests.c
Only check that a point is valid (do the X9.62 checks, for being on the curve, in the correct subgroup, etc) during serialization. Don't repeat them elsewhere, and instead just assume that a point given to, for example, schnorr_verify was obtained via a deserialization and thus is already checked validity.
Also, we no longer do the subgroup-membership check for G2 points. This is because I'm not sure that the technique that had been used before (which was copied from G1 code) is appropriate for this group.
Related to #7 
However, we keep that issue open, because the necessity of doing the checks in G2 and exactly how to do the G2 checks remains open.
=> Do membership checks in deserialization code, only.

examples/file_utils.h
Coverity caught this.
If `fread` or `fwrite` has a problem, we return early, not closing the `FILE` pointer.
=> Fix resource leak in examples/file_utils.h.

.travis.yml, .travis/install-libsodium.sh, README.md
Replace Codecov with Coveralls.
This was done because most of our source code will be generated from template files.
While both tools rely on github to get our source code, and thus can't show us the coverage for the generated files (they're not checked in to git), Coveralls will still include the generated files in the reports.
=> Use coveralls

.travis.yml, .travis/run-cppcheck.sh, README.md, test/benchmarks_ZZZ.c
This performs a much more thorough static analysis of our code.
This PR also updates the way we're using cppcheck, to reflect the recent change to generated source code.
As a result of both of these, the cppcheck check takes ~5x longer than it used to.
=> Use `enable=all` in cppcheck

test/integration-tests.py
The integration script uses xrange, which is only available in Python2.
However, the script has a she-bang saying it's python3.
We didn't see this when runing tests,
because our CTest actually runs it as Python2.
To be consistent, turn xrange into range,
and run the script as Python3.
=> Integration test script uses Python3 and xrange, which is inconsistent.

src/internal/schnorr_ZZZ.c
A comment in `schnorr.c` describing how the hash is constructed when verifying a signature, was incorrect.
=> Correct comment in schnorr.c.

examples/extract_group_public_key.c, examples/file_utils.h, examples/issuer_create_group.c, examples/issuer_respond_to_join_request.c, examples/member_process_join_response.c, examples/member_request_join.c, examples/member_sign.c, examples/verify.c, test/integration-tests.py
For signing and verifying, in our examples, read the message from file rather than directly from the command line.
This allows more complex messages to be signed.
=> Read msg from file

src/tpm-utils/commit.c, test/tpm-test-utils.h
Coverity uncovered two issues with the recent `use-tpm` merge:
- A length check in `commit.c` didn't include the length of an extra `uint32_t` that also got copied into a buffer, allowing a possible buffer overflow (by the size of a `uint32_t`)
- The return value of `ecp_deserialize` wasn't being checked in `tpm-test-utils.h`
=> Fix coverity defects

examples/verify.c, src/tpm_context.c
Fix two issues found the sanitizer builds:
- Make sure to free memory in `verify.c` in the event of a non-zero return
- Do a NULL check before calling memcpy in `tpm_context.c`, since it's valid for the password to be NULL but we don't want to call `memcpy` with that NULL buffer.
=> Fix lsan issues

CMakeLists.txt, README.md, examples/CMakeLists.txt, examples/member_sign.c, examples/verify.c, include/ecdaa.h, include/ecdaa/revocations_ZZZ.h, include/ecdaa/signature_TPM.h, include/ecdaa/signature_ZZZ.h, src/amcl-extensions/big_XXX.c, src/amcl-extensions/big_XXX.h, src/amcl-extensions/ecp_ZZZ.c, src/amcl-extensions/ecp_ZZZ.h, src/internal/schnorr_TPM.c, src/internal/schnorr_TPM.h, src/internal/schnorr_ZZZ.c, src/internal/schnorr_ZZZ.h, src/member_keypair_TPM.c, src/member_keypair_ZZZ.c, src/signature_TPM.c, src/signature_ZZZ.c, src/tpm-utils/commit.c, src/tpm-utils/commit.h, test/benchmarks_ZZZ.c, test/integration-tests.py, test/schnorr_TPM-tests.c, test/schnorr_ZZZ-tests.c, test/signature_TPM-tests.c, test/signature_ZZZ-tests.c
Fixes #5 
This continues to use the Camenisch et al, 2016 algorithm, which always included pseudonyms and linking (the FIDO version removes that capability).
Signatures without pseudonyms are still allowed. If a verifier doesn't use a basename with a signature that was produced with one (or vice versa), the verification will fail. In this way, interop with FIDO is maintained.
=> Add basename revocation

examples/member_sign.c
Coverity found a bug in our examples code. If we can't fail when creating the signature, we also print the message itself to stderr. However, this message is just a uint8_t buffer, and we weren't null-terminating it before casting to char* and printing.
This commit fixes that, by explicitly setting `message[msg_len] = 0`.
=> Before printf'ing message, in examples/member_sign.c, ensure it's null-terminated

.travis.yml, CMakeLists.txt, src/amcl-extensions/ecp_ZZZ.c, src/internal/schnorr_ZZZ.c
Tests using BLS383 were failing, when verifying signatures created using a basename.
The root of the issue is that the `ecp_BLS383_fromhash` function needs to multiply the generated point by the cofactor of the curve group (in order to put the point in the proper subgroup of the full curve group).
For the other curves, this didn't arise, because their cofactors are 1. BLS383, though, has a rather large cofactor.
=> Fix bls383

.travis/run-tpm-simulator.sh, test/tpm-test.c
This also means to use the child-signing-key executable from xaptum-tpm in travis.
For the simulator it makes no difference (this test never broke against
the simulator).
But, this is the way to do it if running against an actual Infineon TPM
(with the broken firmware).
=> Bring back the formerly-breaking part of tpm-test.

src/tpm_context.c
When we de-serialize the public key passed to `tpm_context`, we need to check that it's a proper public key.
=> Check return value from deserialize of pub_key in tpm_context

README.md, examples/member_sign.c, examples/verify.c
Irina found an issue with the verification example, when using a basename file.
The issue is that the signature isn't getting (de)serialized properly in the case of a basename-enabled signature.
=> Fix verify with basenames

CMakeLists.txt, cmake/FindXaptumTPM.cmake
The guards int eh `FindXaptumTPM.cmake` that ensure we only find XaptumTPM once were incorrect, meaning Xaptum-TPM would *never* be properly found! Things were only working because the `xaptum-tpm` directory was in the default location, I guess.
=> Fix find xaptum tpm

CMakeLists.txt, examples/CMakeLists.txt, test/CMakeLists.txt
Previously, if this project were included as a sub_directory of a higher-level CMake project, we would spray our output all over their build directory, rather than into our own directory.
=> Fix bin location

CMakeLists.txt, README.md, test/CMakeLists.txt
Since `BUILD_EXAMPLES` is OFF by default, if someone stock builds this project and then tries to run `ctest`, they'll see integration-tests fail.
So, don't run integration-tests, unless we have the examples.
=> Dont run integration tests unless BUILD_EXAMPLES=ON

CMakeLists.txt, README.md, include/ecdaa/member_keypair_TPM.h, include/ecdaa/tpm_context.h, src/member_keypair_TPM.c, src/tpm_context.c, test/schnorr_TPM-tests.c, test/signature_TPM-tests.c, test/tpm-test-utils.h, test/tpm-test.c
Don't require the serialized public key to create a `tpm_context`.
Instead, require the serialized public key in order to create a `member_key_pair_TPM` (that's where it's actually needed).
Also, improve README on how to run tests using the TPM simulator.
=> Improve tpm api

CMakeLists.txt, src/amcl-extensions/big_XXX.c, src/amcl-extensions/big_XXX.h, src/amcl-extensions/ecp_ZZZ.c, src/amcl-extensions/ecp_ZZZ.h, src/credential_ZZZ.c, src/internal/randomize_credential_ZZZ.c, src/internal/schnorr_ZZZ.c, src/issuer_keypair_ZZZ.c, test/benchmarks_ZZZ.c, test/big_XXX-tests.c, test/credential_ZZZ-tests.c, test/ecp_ZZZ-tests.c, test/member_keypair_ZZZ-tests.c, test/schnorr_ZZZ-tests.c, test/signature_TPM-tests.c, test/signature_ZZZ-tests.c, test/tpm-test.c
Make `random_mod_order` part of ecp extensions, not big extensions.
That function depends on the order of the specific curve, not just the
type of BIGNUM being used. Thus, we need a different function for each
curve, not just each big.
Having just one for each big was causing linking problems (we really need separate functions, but since they were getting named the same thing they were clobbering each other).
=> Fix random mod order collision

CMakeLists.txt
The `ecdaa-dev` package requires `xaptum-tpm` header files, so add a dependency on the `xaptum-tpm-dev` package.
=> Add xaptum tpm dev dep

CMakeLists.txt, include/ecdaa/tpm_context.h, src/tpm_context.c, test/CMakeLists.txt, test/tpm-test-utils.h
Take a pointer to a TCTI context when initializing a tpm_context, rather than initializing the TCTI context internally.
This allows us to be agnostic about whether it's a TCP socket, or dev file, or whatever.
=> Move out tcti

test/tpm-test-utils.h
Upstream AMCL has typedefed `byte` to an 8-bit type, conflicting with
it's use a variable name.
Fixes #85
=> test: do not use byte as variable name

.travis/install-libsodium.sh, README.md
We had required 1.0.13 earlier, because that was the most-up-to-date
at that time.
However, Debian 9 ships with 1.0.11, so it would be nice to only require
that high.
Luckily, building with 1.0.11 works.
=> Decrease required version of libsodium, from 1.0.13 to 1.0.11.

src/prng.c
Note, in the course of creating this commit, I discovered that setting `DISABLE_LIBSODIUM_RNG_SEED_FUNCTION` keeps essentially all of the tests from compiling.
So, currently, this commit can't be tested. 
This issue will be fixed in the upcoming work to update how we take randomness (issue #96).
=> Ensure that limits.h is included in prng.c, even when not using sodium

CMakeLists.txt, examples/CMakeLists.txt
We were still wrapping the CMake install call for the examples in a `if (NOT BUILD_SHARED_LIBS)`.
=> Install examples

CMakeLists.txt, cmake/Findsodium.cmake
Findsodium uses the following to see if the user has specified the name of the sodium libraries (I don't know why it allows that, but it does):
`if (sodium_LIBRARIES STREQUAL "")`
If this is true, then it sets it to the reasonable default `sodium`.
The problem is that if `sodium_LIBRARIES` is not even set, then this is untrue, so `sodium_LIBRARIES` never gets set, and we call `find_library` on an unset variable (and thus never find that library).
This fixes that by explicitly augmenting that check to
`if (NOT DEFINED sodium_LIBRARIES OR sodium_LIBRARIES STREQUAL "")`
=> Be careful comparing CMake strings to empty, in Findsodium

CMakeLists.txt, examples/CMakeLists.txt
This is to avoid polluting the global variables
=> Set compiler flags (e.g. -std= and -Werror) as add_compile_options.

.editorconfig
Configuration file for EditorConfig that specifies the indenting-style preferred in this project. Plugins are available for most popular editors to enforce this style.
=> Add editorconfig.org file

.travis.yml, .travis/install-ibm-tpm2.sh, .travis/prepare-tpm2.sh, .travis/run-ibm-tpm2.sh, README.md, benchmarks/benchmarks_ZZZ.c, libecdaa-tpm/member_keypair_TPM_ZZZ.c, libecdaa-tpm/schnorr-tpm/schnorr_TPM_ZZZ.c, libecdaa-tpm/schnorr-tpm/schnorr_TPM_ZZZ.h, libecdaa-tpm/signature_TPM_ZZZ.c, libecdaa/include/ecdaa/member_keypair_ZZZ.h, libecdaa/include/ecdaa/signature_ZZZ.h, libecdaa/member_keypair_ZZZ.c, libecdaa/schnorr/schnorr_ZZZ.c, libecdaa/schnorr/schnorr_ZZZ.h, libecdaa/signature_ZZZ.c, test/schnorr_ZZZ-tests.c, test/tpm/CMakeLists.txt, test/tpm/create_tpm_key-util.c, test/tpm/schnorr_TPM_ZZZ-tests.c, test/tpm/tpm_ZZZ-test-utils.h, test/tpm/tpm_ZZZ-test.c
More-recent TPM2.0 specifications include a change to the TPM2_Sign operation that breaks the old implementation of this library. This series updates our implementation to accord with that change.
fixes #112
=> Update signing algorithm to work with TPM spec 1.38 (and 1.16 with Errata 1.5)

libecdaa-tpm/schnorr-tpm/schnorr_TPM_ZZZ.c, libecdaa-tpm/tpm/commit_ZZZ.c
When reading the output from TPM_Commit and TPM_Sign, the output values are raw buffers with 2-byte size values preceding them.
Previously, we were assuming constant sizes for these buffers, which most likely should be true in the usual circumstances.
However, we can use the length-checked version of the AMCL deserialization function that we were already using (with no run-time cost) to leverage the size values we already have, just to make sure we don't have any buffer overflows.
This series introduces this length-checking, so that we *should* now be sanitizing all output received from the TPM.
=> Use length-checked version of AMCL deserialization when reading output from TPM

.travis.yml, libecdaa-tpm/schnorr-tpm/schnorr_TPM_ZZZ.c, libecdaa-tpm/schnorr-tpm/schnorr_TPM_ZZZ.h, libecdaa-tpm/tpm/sign.h, libecdaa/schnorr/schnorr_ZZZ.c, libecdaa/schnorr/schnorr_ZZZ.h, test/CMakeLists.txt, test/schnorr_ZZZ-fuzz.c, test/tpm/CMakeLists.txt, test/tpm/schnorr_TPM_ZZZ-fuzz.c, test/tpm/schnorr_TPM_ZZZ-tests.c
The recent changes to the Schnorr signature primitive (underlying the actual DAA signature) that were made to work with recent TPMs exposed some issues with the Schnorr signatures:
- Our implementation was missing a modular-reduction of one of the hash outputs during signature generation, which intermittently caused valid signatures to fail verification (particularly for the 254-bit curves)
- The TPM spec appears to specify that the nonce generated during TPM_Sign can be fed into the final hash as a variable-length encoding. Our implementation, however, was assuming that the nonce is always 32bytes (cf. [this discussion](https://github.com/xaptum/ecdaa/pull/116#issuecomment-437149049))
This is only of concern in the somewhat-rare (~1/256 probability) event that the randomly-generated …
=> Fix transient issues with Schnorr signature primitive

.travis.yml
This changes the format of the `.travis.yml` to implement a build matrix in order to make it slightly cleaner. It also adds a test case for building the static library and adds a local install with each build.
=> Add local install and build static library tests to travis

.travis.yml, .travis/build-against-installed.sh, libecdaa-tpm/CMakeLists.txt, libecdaa/CMakeLists.txt
This fixes a reversion from commit 65c45de.
When we removed non-templated header files from being processed by the expander, that also meant they weren't getting copied into the build directory. During building, this was OK because we also added the source directory to the include directories. However, because we install *only* the include directories under the build directory, this meant the non-templated (but part of the public API) header files weren't installed.
=> cmake: Install non-templatized header files.

tool/verify_ZZZ.c
The `verify` file in the `tool` subproject still had a hardcoded `256_56` rather than a `XXX`.
@drbild would you mind trying a build of this branch on a 32bit arch, to make sure this fixes your issue?
fixes #127
=> Properly templatize tool files.

CMakeLists.txt, README.md
Some of the `BUILD_xxx` options were either not explicitly declared in `CMakeLists.txt` or documented in the README.  This series fixes those inconsistencies.
=> Update options and docs

.travis.yml, .travis/install-amcl.sh
Same change as in PR as [#115 in XTT](https://github.com/xaptum/xtt/pull/115) and [#2 in homebrew-xaptum](https://github.com/xaptum/homebrew-xaptum/pull/2)
=> Change AMCL url since the original is not supported

.travis.yml, .travis/install-tpm2-tss.sh, CMakeLists.txt, cmake/FindTSS2.cmake, cmake/LibFindMacros.cmake, doc/BUILDING.md, doc/TESTS.md, ecdaa-config.cmake.in, libecdaa-tpm/CMakeLists.txt, libecdaa-tpm/include/ecdaa-tpm/tpm_context.h, libecdaa-tpm/tpm/sign.c, libecdaa-tpm/tpm_context.c, test/member_keypair_ZZZ-tests.c, test/tpm/CMakeLists.txt, test/tpm/create_tpm_key-util.c, test/tpm/tpm_ZZZ-test-utils.h, tool/member_sign_ZZZ.c
This PR transitions this project from using `xaptum-tpm` for the "TSS" (TPM Software Stack), to the official `tpm2-software/tpm2-tss` (this is the implementation available via APT on Debian-based systems, for example).
~~TEMPORARY: The build is still failing, because Valgrind Memcheck is complaining about some uninitialized memory usage in the `tpm2-tss` library. I'll track that down (either figure out if it's our fault, or silence the warnings). But I wanted to get your feedback on the CMake stuff~~
UPDATE: The uninitialized memory usage warning from Memcheck is happening in the tpm2-tss library's "mssim" TCTI (this is the TCTI that communicates with the software simulator we run). I checked that it doesn't arise when running against a device TPM, so it appears to be just concerning the …
=> Use `tpm2-software/tpm2-tss` rather than `xaptum-tpm`

libecdaa-tpm/include/ecdaa-tpm/signature_TPM_ZZZ.h, libecdaa-tpm/schnorr-tpm/schnorr_TPM_ZZZ.c, libecdaa/include/ecdaa/signature_ZZZ.h, libecdaa/schnorr/schnorr_ZZZ.c, test/signature_ZZZ-tests.c, test/tpm/signature_TPM_ZZZ-tests.c
This PR:
- Clarifies (well, actually states) the documentation for the `sign` and `verify` functions when used with "unlinkable" signatures, i.e. not using a `basename`
- In such cases, *both* `basename == NULL` *and* `basename_len == 0` must be true
- Makes the checks for those conditions in the code a little more explicit
- Previously, this check was done in only one sub-function, and so was a little implicit
- Adds tests for this functionality
This was spurred by Issue #135
=> Clarify usage of sign and verify for unlinkable signatures

test/tpm/create_tpm_key-util.c
This PR ensures that all structs used in the `create_tpm_key-util` utility program are zero-initialized before use.
This utility is only used when running tests against physical TPMs, when it's run manually to create the necessary key.
The same changes were already made to the test files used when testing against a software TPM simulator. I just had forgotten to make these changes here.
cf. Issue #137
=> test: Zero-initialize all structs passed to TSS lib.

common/amcl-extensions/ecp_ZZZ.c, common/amcl-extensions/ecp_ZZZ.h, test/schnorr_ZZZ-fuzz.c, test/tpm/schnorr_TPM_ZZZ-fuzz.c
While little-by-little trying to update this project to the newest literature, I noticed an issue with our hashing-to-a-curve-point in the case of curves with a cofactor not-equal to 1.
As before, if the cofactor is not-equal to 1, we multiply a putative point by the cofactor to ensure we're on the prime-order sub-group. However, I believe the resulting prime-order point could wind up being the identity (basically, if the initial point has no component in the prime-order subgroup, as a direct sum)! So, in the original version of this code, I forgot to explicitly check that we haven't ended up with the identity.
This is a pretty rare (~ 1/subgroup-prime-order probability) outcome if given random hash input. However, that hash input comes from the user (it's the basename), so it's not …
=> Check for identity during hashing-to-point
